@startuml domain-model

' hide the spot
hide circle

rectangle チーム集約 {
  entity チーム {
    チームID
    名前
    List<ペアID>
    List<参加者ID>
  }
}
note left of チーム
- 名前は3桁以下の数値かつ重複不可
- 参加者は最低3名
end note

rectangle ペア集約 {
  entity ペア {
    ペアID
    名前
  }
  entity ペア所属参加者 {
    ペアID
    参加者ID
  }
}
note top of ペア
- 名前は1文字の英字
- 参加者は2名〜3名
end note


rectangle 参加者集約 {
  entity 参加者 {
    参加者ID
    名前
    メールアドレス
    在籍ステータス
  }
}
note top of 参加者
- メールアドレスは重複不可
- 在籍ステータスは「在籍中、休会中、退会済」
- ステータスが「在籍中」以外の場合
  どのチームにもペアにも所属できない
end note

rectangle 課題集約 {
  entity 課題 {
    課題ID
    タイトル
    本文
  }
}

rectangle 参加者所有課題進捗ステータス集約 {
  entity 参加者所有課題進捗ステータス {
    参加者ID
    課題ID
    進捗ステータス
  }
}
note right of 参加者所有課題進捗ステータス
- 進捗ステータスは「未着手、レビュー待ち、完了」
- 「完了」から「レビュー待ち、未着手」に戻せない
- 課題の所有者のみ進捗ステータスを変更できる
end note

チーム --> ペア
チーム --> 参加者
ペア *-- ペア所属参加者
参加者 <-- ペア所属参加者
参加者 <-- 参加者所有課題進捗ステータス
課題 <-- 参加者所有課題進捗ステータス

@enduml
